# Review Tasks for the lecture

Here some small tasks with that you should be able to do directly after the lecture. I strongly advise you to look at them before the exercise. It gives you the opportunity to check what you did not yet understand and to ask your tutor in the case of problems.

## 1. Review tasks on multi-dimensional `numpy`-arrays

**Please try to answer the following questions before executing any code. Do this only to verify your answers and use appropriate help-utilities if you are uncertain! For each problem you should be able to explain WHY you obtain a certain result!**

- What is the output of the follwing code:
  ```
  import numpy as np
  
  a = np.ones(30).reshape((6, 5))
  
  print(a * a)
  print(a.dot(a.T))  # a.T transposes 'a'
  print(a.sum())
  print(a.sum(axis=0))
  print(a.mean(axis=1))
  ```

- What is the result of the following code:
  ```
  import numpy as np
  
  a = np.ones(30).reshape((6, 5))
  b = np.arange(30).reshape((6, 5))
  
  a[b <= 4] = 100
  print(a)
  ```

- What is the result of the following code:
  ```
  import numpy as np
  
  a = np.zeros(36).reshape((6, 6))
  a[:, [1, 2]] = 1
  
  print(a)
  ```

- What is the output of the following code:
  ```
  import numpy as np
  
  a = np.zeros(36).reshape((6, 6))
  a[:,::3] = 1
  a[::3,:] = 1
  
  print(a)
  ```

- What is the output of the following code:
  ```
  import numpy as np
  
  a = np.zeros((2, 5))
  a[1,:] = 1
  
  mask = a.sum(axis=1) > 1
  a[mask,:] = 100
  
  print(a)
  ```

### Creation of multidimensional numpy-arrays

Use a maximum of three commands for each of the following:

- Create a 2d-array of size $10\times 10$ with 1 on the border and zero inside.
- Create a $5\times 5$ matrix with the values $1, 2, 3, 4$ below the main diagonal and zero everywhere else.
- Create a $8\times 8$ checkerboard matrix with zeros and ones.

### Slicing of 2d arrays

- Read the file [data/slicing.txt](data/slicing.txt) into a two-dimensional `numpy`-array `a`.
- Obtain the sub-arrays indicated by different colors with one numpy slice-command on `a` for each case.

<img src="figs/slicing.png" style="width: 400px;" style="height: 400px;">

In [ ]:
# Your solution here please

---

## 2. Review tasks on `numpy`-internals and `numpy`-functions

### Rolling window

The `rolling window` technique is somewhat special to numpy-arrays. One typical task is, that you want analyse a special part of a 1d-array, which is called window. Of course you can use slicing operations to move a window over the complete array, but this is not the best pythonic way. The idea of the `rolling window` is to create a new view, which gives you access to all possible windows of the 1d-array. 

Assume an array like this:
```
[0 1 2 3 4 5 6 7 8 9]
```

After the windowing task, you will have a 2d-(pseudo)-array like this:
```
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]
```

The `numpy` function `np.lib.stride_tricks.as_strided` can create a new view on the data:

```
new_view = np.lib.stride_tricks.as_strided(old_array, shape=new_shape, strides=new_strides, writeable=False)
```
(`writeable=False` is used for safety reasons, if will create a read only view!)


**Your task:**

Write a function `rolling_window` which takes the original data and the number of elements in the window `size` as arguments. The return value should be the new view of the data. You have to find a proper setup for `new_shape` and `new_strides` which can be defined with the original values.
Reproduce the previous output for the test array.

**Hints:**
 * create your solution on a piece of paper to see how the values must be set
 * for the `shape` and `strides` have a look at the [lecture materials](Python_tutors_SS2023/week05/03_numpy_intern.ipynb) itself!

In [ ]:
a = np.arange(0,10,1)
print(a)

# You solution here please

### `np.isclose` on `numpy`-arrays

You know alread `np.isclose` on values as a replacement for a `==` comparison. Assume the following 2d-array:

```
[[0 1 2 3]
 [0 1 2 2]
 [1 2 1 1]
 [2 1 2 1]
 [2 0 2 2]]
```

It is possible to check with `np.isclose` if there is array `t=[1,2,1,1]` inside the array. `numpy` checks in this case every row with the array `t` and gives the result as a boolean array with the same dimension as `a`. The parameter `atol=limit` can be used to control the check of `np.isclose`. 

**Task:**

When you check the array `a` of the occurence `t` a 2 dimensional result is not really helpful. Apply the same strategy as for comparisons of numpy arrays in week 4 and collapse the results into a linear array!

In [ ]:
# Your solution here please

---

## 3. Review tasks for Python `strings`

**Please try to answer the following questions *before* without running any code. Only do so to verify your answer.**

- What is the output of the following code:
  ```python
  s = "Jane Doe"
    
  print(s[1], s[2:6], s[-1])
  print(s[20])    
  ```

- What is the output of the following code:
  ```python
  n = 12345
  s = 0

  for c in str(n):
      s = s + int(c)
    
  print(s)    
  ```

  **Note:** The function `int` converts a string to an integer number (if possible).
  
- What is the output of the following code:
  ```python
  n = 12345
  s = ""

  for c in str(n):
      s = s + c
    
  print(s)    
  ```
 

In [ ]:
# You can use this cell for tests

## Multiplication tables

The following code prints out a multiplication table

In [ ]:
i = 1

while i <= 10:
    j = 1
    while j <= 10:
        # Note the 'end'-parameter in teh follwing print-statement
        # What does it do?
        print(i * j, end=" ")
        j = j + 1
    i = i + 1
    print() # just print a newline

Modify the code so that the following form of the table is printed.

**Hint:** f-strings

```
001 002 003 004 005 006 007 008 009 010 
002 004 006 008 010 012 014 016 018 020 
003 006 009 012 015 018 021 024 027 030 
004 008 012 016 020 024 028 032 036 040 
005 010 015 020 025 030 035 040 045 050 
006 012 018 024 030 036 042 048 054 060 
007 014 021 028 035 042 049 056 063 070 
008 016 024 032 040 048 056 064 072 080 
009 018 027 036 045 054 063 072 081 090 
010 020 030 040 050 060 070 080 090 100
```

## Task 8 of Project Euler

[Project Euler](https://projecteuler.net) is a great source for programming tasks at all levels. Please solve [problem 8](https://projecteuler.net/problem=8) which is a great application for operations with the Python string type.

**Hint:** The second task of the `strings`part of this notebook shows you how to calculates the crosssum of an integer number. For this problem, a similar code-block to obtain the  `cross_product` of an integer will come in very handy.

In [ ]:
# your solution here

# The variable 'number' below contains the 1000-digit
# number of the Euler-problem as a string

number = """
73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450
"""