# Numpy-Addons

---

In this notebook we want to briefly address a few additional things:

 * random numbers
 * brief introduction of multi-dimensional arrays

---

## 1. Random numbers

A sub modul of `numpy` provides the access to random numbers:

In [10]:
# standard header

import numpy as np
import numpy.random as nr


print(nr.random(size=5))   # create 5 random numbers between 0 and <1 (open intervall)
print(nr.uniform(size=5))  # the same ;-)

[0.23703882 0.67681703 0.73267367 0.82697655 0.53752451]
[0.21625109 0.91461341 0.96265383 0.76715558 0.67394131]


`nr.random` creates *uniform* random numbers, whereas `nr.normal` creates random numbers which follows a gaussian distribution:

In [11]:
# standard header

import numpy as np
import numpy.random as nr

print(nr.normal(5,1,size=10))  # create 10 random numbers with a locus of 5 and width of 1

[3.70461266 5.82476628 5.10473351 5.44327257 3.46298127 4.83045628
 6.23870633 6.46644158 5.48337018 3.66027847]


---

## 2. Multi-dimensional arrays

In the previous lecture we have introduced 1d-`numpy`-arrays. In many cases it is necessary to have multi-dimensional arrays, e.g. matrices which can be represented as 2d-arrays. The general syntax in the creation is, that one defines a starting axis and the elements are not numbers but also arrays. So you can define recursively multi-dimensional arrays:

In [2]:
import numpy as np

a = np.array([[1,2], [3,4]])   # creation of a 2d array, keep an eye on the brackets!

print(a)

[[1 2]
 [3 4]]


Indexing of multi-dimensional arrays is as easy as for 1d-arrays:

In [5]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8]])

print(a)
print(a[0,0])  # first element, first row
print(a[1,-1]) # last element, second row

[[1 2 3 4]
 [5 6 7 8]]
1
8


Indices for all dimensions have to be comma separated, starting with the first axis.

In [7]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8]])

print(a)
print(a[0])     # access the first row completely
print(a[:,1])   # access the second column completely, the : is indicating all values!

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
[2 6]


Modifying arrays is working similar. You can simply transfer all methods from the 1d-arrays to the multi-dimensional arrays.

**Note:** Alls mathematical operations on multi-dimensional arrays are working elementwise!

---

For one of the coming projects it is necessary to initialize special arrays which holds the position $r = (x,y)$ and velocities $v=(v_x,v_y)$ for $N$ objects, lets have a look at an example with $N=10$:

In [23]:
import numpy as np
import numpy.random as nr

N = 10
r = nr.random(size=(2,N))  # create a 2d array with all information

print(r)

[[0.01276241 0.18190411 0.35842044 0.76091004 0.03723948 0.64821526
  0.47704637 0.49869549 0.0179028  0.71122818]
 [0.11757684 0.51821668 0.71576306 0.27031487 0.7401418  0.9007943
  0.62067077 0.31826053 0.50368039 0.0397421 ]]


In this case size is not a number, but gives a layout of the created array, two rows with $N$ columns.

If you need for example all $x$ positions in an array back, you can use:

In [24]:
x = r[0]  # the x positions of all N objects 
y = r[1]  # the y positions of all N objects

print(x)
print(y)

[0.01276241 0.18190411 0.35842044 0.76091004 0.03723948 0.64821526
 0.47704637 0.49869549 0.0179028  0.71122818]
[0.11757684 0.51821668 0.71576306 0.27031487 0.7401418  0.9007943
 0.62067077 0.31826053 0.50368039 0.0397421 ]


On the other hand, if you want to address the second object directly with the complete position:

In [25]:
print(r[:,1]) # prints the vector belonging to the second object

[0.18190411 0.51821668]


Updating all $x$ positions at the same time can be done with this command:

In [26]:
print(r)
r[0] += 10    # change only the x positions
print(r)

[[0.01276241 0.18190411 0.35842044 0.76091004 0.03723948 0.64821526
  0.47704637 0.49869549 0.0179028  0.71122818]
 [0.11757684 0.51821668 0.71576306 0.27031487 0.7401418  0.9007943
  0.62067077 0.31826053 0.50368039 0.0397421 ]]
[[10.01276241 10.18190411 10.35842044 10.76091004 10.03723948 10.64821526
  10.47704637 10.49869549 10.0179028  10.71122818]
 [ 0.11757684  0.51821668  0.71576306  0.27031487  0.7401418   0.9007943
   0.62067077  0.31826053  0.50368039  0.0397421 ]]


Also masking works fine for $x$ positions selections. Change only $x$ values which are larger than `0.5`:

In [15]:
N = 10
r = nr.random(size=(2,N))  # create a 2d array with all information

print(r[0])

mask = r[0] > 0.5   # x > 5
r[0,mask] += 10

print(r[0])

[0.38673008 0.84130512 0.66678384 0.94867973 0.52456688 0.10021775
 0.13854047 0.92200934 0.46187114 0.42334037]
[ 0.38673008 10.84130512 10.66678384 10.94867973 10.52456688  0.10021775
  0.13854047 10.92200934  0.46187114  0.42334037]


---