# The ideal gas (simulation in 2d)

**Project deadline:** This project is due for submission on Thursday, 11.05.2023, 23:55. Please check carefully the *About the Projects* section below for further details.

**Important:** You have the choice to work either on this project from Oliver Cordes  or on another one from Thomas Erben. We strongly advise you to read through both project notebooks completely before you take a decision.

## About the Projects
- You will get one project approximately every other week.
- Besides the homework-asignmentts, you need to solve the projects in order to pass the course. Your final course mark consists of the mean of your project marks. We aim to hand-out five projects during the term and we do not consider the worst project mark for your final course mark. Projects that you do not hand in are counted with a mark of 4.
- The projects needs to be submitted by uploading a modified version of this notebook to [Projects/Project 1](https://ecampus.uni-bonn.de/goto_ecampus_exc_3025921.html) on eCampus. Please only upload this notebook and no other files. You also do not need to change its filename before your upload. Your project must be on eCampus by Thursday, 11.05.2023, 23:55. **No late uploads can be accepted!**
- **In contrast to the homework exercises, each student must hand in an own solution for the projects! Of course you can and should discuss problems with each other! However, you need to be able to explain your solution in detail to your tutor and/or the lecturers! We might ask you for an interview about your project if the solution is (close to) identical to another students submission.**

**Note:** The tutors, Thomas and I are very happy to help you out with difficulties you might have with the project tasks! You can ask questions any time but please do so well in advance of the deadlines!

**Important:** Your notebook will be tested and graded from a *clean* state `(Kernel -> Reset Kernel and clear all Outputs)`. Please make sure that it cleanly runs from *top to bottom*!

### Your Name here please:

## Introduction

The ideal gas is a wonderful platform to study the behavior of particle collisions and also to verify the rules of thermodynamics. From the programming aspect it a nice project to understand the technique of indexing and masking in combination with some math algorithms. 

The simulation in this notebook is just a start to simulate physical process and you can simply think of enhancements which you can add to the code.

# Project 1 - The ideal gas (simulation in 2d)

In this project we want to simulate an ideal gas and checks if we can demonstrate that in the simulation a homogeneous velocitiy distribution converge into the Maxwell-Boltzmann distribution.

## 1. The decentral inelastic collision (2d)

For the collision we assume the following scenario. A mass $m_1$ with the velocity $\vec{v}_1$ have a collision with a second mass $m_2$ with a velocity $\vec{v}_2=0$. To transfer all other situation into this scenario you can use the velocity difference of the two masses as $\vec{v}_1$ and assuming that we have moving laboratory system!

You can simply calculate from the conservation of energy and momentum with $m_1 = m_2 = m$ that the former velocity vector $\vec{v}_1$ is splitted into the two resulting velocity vectors $\vec{v}'_1$ and $\vec{v}'_2$ which are orthogonal to each other. 

<center>
<img src="figs/decentralcoll.png" style="width:50%">
</center>

To calculate the resulting vectors we can use simple linear algebra. The projection of the vector $v_1$ on the vector between the two masses $r$ can be written as $v'_r$. Then the new velocity vectors are:

\begin{align}
\vec{v}'_1 & = \vec{v}_1 - \vec{v}'_r \\
\vec{v}'_2 & = \vec{v}'_r 
\end{align}


$v'_r$ as a projection can be calculated with:

\begin{align}
\vec{v}'_r = \frac{(\vec{v}_1 \cdot \vec{r}) \vec{r}}{\lvert\lvert \vec{r} \rvert\rvert^2} = \frac{(\vec{v}_1 \cdot \vec{r}) \vec{r}}{\vec{r} \cdot \vec{r}}
\end{align}

To move back from the moving laboratory system into the real system, you need to add $\vec{v}'_r$ to the second and substract $\vec{v}'_r$ from the first velocity. This formular is working for any velocity differences $\vec{v}_1$.

To simulate the decentral inelastic collision in Python the best is to define a function in which we can calculate the projected velocity vector $\vec{v}'_r$ corresponding to the position difference $\vec{r}$ and velocity difference $\vec{v}_1$. 

**Task:**

Write a function `collision` which takes the velocity and the position as arguments and returns the projected velocity.

Test the function with some configurations for which the results you already know (put the tests inside your solution cell with a description):
 * central collision ($\vec{v}_1 = [1,0]$ and $\vec{r}=[1,0]$)
 * 45 degrees collision ($\vec{v}_1 = [1,0]$ and $\vec{r}=[1,1]$)
 * double velocity for central collision and 45 degrees collision
 * create your own test (no duplication of the prior tests)

**Hints:**
 * for a vector you can use a 1d numpy array

In [13]:
# Your solution here please

----

## 2. The ideal gas (2d)

In the second task we want to simulate how a number of $N$ particles behaves like an ideal gas. We want to show that during the simulation the starting homogeneous velocity distribution converges into a Maxwell-Boltzmann distribution ([see this Wikipedia article](https://en.wikipedia.org/wiki/Maxwell%E2%80%93Boltzmann_distribution)). 

Inside the simulation we want to take into account collisions with the walls and with other particles. Rotation, friction and other external forces will be excluded. The simulation should start with a homogeneous velocity distribution.

In this task we will develop the simulation step by step while adding new features.

### 1. Setup the simulation

In this first setup we need to prepare all necessary variables for the simulation. 

We start with $N$ particles (for test purposes use $N=10$ in the beginning, you can change it afterwards). For the simulation, we need a position $r$ and a velocity vector $v$ for each particle (both vectors have an $x$ and a $y$ component). 

**Task:**
 * setup a vector $r$ (with $x$ and $y$ components) for $N$ particles which are in a box with a length `box_len=10`; the positions should follow a uniform distribution
 * setup a vector $v$ (with $x$ and $y$ components) for $N$ particles  between `0` and `v_max=0.3` (also with a uniform distribution)
 * setup a simulation loop with a total time `T_max = 100` and a step size `dT = 0.5` for each simulation step
 * in each step do an update of the position $r$ according to the values in $v$ with $r = r + v dT$

**Hints:**
 * have a look at the lecture materials to find a proper way to setup the arrays
 * `r[1]` should return a 1d-array with 2 elements
 * all calculations can be done with numpy commands, don't use loops (except for the simulation loop!)

In [17]:
# Your solution here please

### 2. Wall collision

The first feature to add is the *wall collision* . If a particle hits a wall, the velocity will be reverted. 

**Task:**

Enhance the previous simulation with the *wall collision* feature.

**Hints:**
 * you need to check the wall collision for the $x$ and $y$ component separately
 * use *numpy masking* to find particles which are affected by the collisions
 * have a look at masking on different arrays in the lecture materials
 * In case of a wall collision, only the corresponding component needs to be updated
 * the wall collision should take place before the update of the position!

In [ ]:
# Your solution here please

### 3. First animation

At this point we want to create a first animation with the data, where we want to show the positions of particles. To make the code as simple as possible, we can use previous code with some modifications. The idea is to save all positional data in each step in a numpy array which is then used by the animation routines for the animation.

**Task**: 

Use the simulation and create an animation from the result. Make a simple plot for all particles for each simulation step.

**Hints:**
 * for saving the positions, create an array for all steps of the simulation
 * to fill this array, you need to iterate over an integer other than the time variable before

In [ ]:
# Your solution here please

### 4. Particle collision

All particles perform inelastic collisions with other particles. In Task 1 we described how to calculate the change in velocity for two colliding particles. The implementation of a collision detection algorithm for 2 circular particles only is quite simple. One needs to check the distance between the both centers of mass and check if this is less than the radius of the particles (assume both have the same radius!). 

For $N$ particles we have to check more or less each combination of possible collision partners, that are $\frac{N(N-1)}{2}$ collisions. (Remember that this means the number of computations is proportional to the square of the number of particles $\propto N^2$!)


For this we can use a numpy trick, which automatically creates all combinations. For this we create a copy of $x$ and $y$ and write the vectors as column vectors instead of row vectors, i.e. the standard numpy array. We can now substract the swapped vector from the original vector, `numpy` is creating a matrix for us in which all difference combination will appear.  

If we do this with $x$ and $y$ separately, we can calculate the real distance between two particles. The diagonal elements are always zero, because this is the difference between two identical elements.

From this matrix we can create a mask, which selects all matrix elements whose values are below a certain distance. If you check the mask you will recognize that for all collisions two positions will have `True`. This is because we calculate all combinations $(i,j)$, so if $(i,j)$ is a collision, so is $(j,i)$! 

The next idea is to extract all combinations in an array, which we can use for the next step in our simulation. `np.nonzero` gives us two index arrays which have the positions of the elements which are `True`.

`np.triu` will select only the part of the matrix which is above the diagonal elements, so we have only individual combinations. `np.transpose`  then will create an 2d-numpy-array which gives us the possibility to use the result for fancy indexing of the positions and of course also of the velocities.

Have a close look at the following code to understand what is calculated.

In [7]:
r = np.array([[2,1,3,4], [1,0,2,1]])

radius = 2

# get the distance in x- and y-dimension
dx = r[0]-r[0,:,np.newaxis]
dy = r[1]-r[1,:,np.newaxis]
# calculate the absolute (radial) distance b/w particles
d = np.sqrt(dx**2+dy**2)
print(d)

# mask collisions & neglect "self-collisions"
mask = (d < 2*radius) & ( d>0)

# extract indices of colliding particles
ic = np.transpose(np.nonzero(np.triu(mask)))
print(ic)

# use the indices to get the positions of colliding particles,
# where r1 are those of particle i and r2 those of particle j
r1 = r[:,ic[:,0]]
r2 = r[:,ic[:,1]]
print(r1)
print(r2)

[[0.         1.41421356 1.41421356 2.        ]
 [1.41421356 0.         2.82842712 3.16227766]
 [1.41421356 2.82842712 0.         1.41421356]
 [2.         3.16227766 1.41421356 0.        ]]
[[0 1]
 [0 2]
 [0 3]
 [1 2]
 [1 3]
 [2 3]]
[[2 2 2 1 1 3]
 [1 1 1 0 0 2]]
[[1 3 4 3 4 4]
 [0 2 1 2 1 1]]


To calculate the projected velocity after a collision for $M \in N \times N$ particle pairs at the same time, we have to look at some math equations. For the collision we define $\vec{d_m} = \vec{r_i} - \vec{r_j}$ and $\vec{dv_m} = \vec{v_i} - \vec{v_j}$ with $m \in M$. 

We assume two matrices $A$ and $B$. If we do $C = A \cdot B$, we can write:

$$ c_{ik} = \sum_{j} a_{ij} b_{jk} $$

$A$ and $B$ should be compatible with the multiplication.

If we now use our predefined vectors for the positions and velocities $\vec{d_m}=(x_m,y_m)$ and $\vec{dv_m}=(\dot{x}_m, \dot{y}_m)$ we can perform this matrix multiplication:

\begin{align}
 C & = dv^T \cdot d \\
 c_{mn} & = \sum_l dv^T_{ml} d_{ln} \\
   & = \sum_l dv_{lm} d_{ln}
\end{align}

If we now look at the diagonal elements of this new matrix $j=k$:

\begin{align}
 c_{mm} = c_m &= \sum_l dv_{lm} d_{lm} \\
   c_m &= \vec{dv}_m \cdot \vec{d}_m
\end{align}

The result gives us exactly the wanted inner product of position $r$ and velocity $v$ for each particle $i$. 

To implement the method in Python we need three new functions/commands:
 * `.T` calculates the transposed version of a matrix
 * the operator `@` on two 2d arrays calculates the matrix multiplications
 * `np.diag` returns the diagonal elements of a matrix as an array
 
Have a look at the small example and to check how these commands are working.

In [8]:
r = np.array([[2, 1, 3, 4], 
              [1, 0, 2, 1]])
v = np.array([[1.2, 1.1, 1.0, 1.2], 
              [1.0, 1.0, 1.0, 1.0]])

print(r)
print(v.T)
print(v.T@r)
print(np.diag(v.T@r))

[[2 1 3 4]
 [1 0 2 1]]
[[1.2 1. ]
 [1.1 1. ]
 [1.  1. ]
 [1.2 1. ]]
[[3.4 1.2 5.6 5.8]
 [3.2 1.1 5.3 5.4]
 [3.  1.  5.  5. ]
 [3.4 1.2 5.6 5.8]]
[3.4 1.1 5.  5.8]


**Task:**

Implement the particle collision technique in the prior simulation and check if you can see particles colliding. It is useful to increase the number of particles now to $N=100$.

**Hints:**
 * use a particle size of `0.1` for the collision detection

In [87]:
# Your solution here please

---

### 5. Maxwell-Boltzmann distribution

After the first animation we want to demonstrate now, that after a certain number of timesteps the uniform absolute velocity distribution in our ideal gas simulation will converge to a Maxwell-Boltzmann distribution.

**Task**:

Use the prior simulation and create a new animation in which you use the histogram function of matplotlib to show how the velocity distribution evolves in time.

**Hints:**
 * the calculation of histograms takes some time, maybe start with a few simulation steps in the beginning
 * a recommended option to improve the performance of `ax.hist()` is `histtype='step'`
 * take a closer look at the first histogram of your animation -- it must resemble a uniform distribution!
 * if it is not uniform, maybe you did not assign the velocities correctly; the absolute velocity $||\vec{v}||$ must be sampled uniformly as well as the direction $\theta$, such that $\vec{v} = ||\vec{v}|| \cdot (\cos\theta, \sin\theta)^T$

In [14]:
# Your solution here please

---